### PR TITLE
Implement encryption

### PR DESCRIPTION
**Pull request by Rawleenc**
TO-DO LIST:

- [x] Add encryption informations in partition class
- [x] Make the partition class contain the partition formatting and mounting intelligence
- [x] Add a boot partition type in the manual partitioning
- [x] Refactor the partitioning_info dict to use the partition class and add all required informations into it
- [x] Refactor the manual partitioning to ask if encryption is desired for each encryptable partitions. If encryption is desired then it is not possible to not format the partition
- [x] Refactor the automatic partitioning to ask if encryption is desired for root and home if separated home is chosen
- [x] Add the generation of a boot partition in automatic partitioning if root is encrypted
- [x] Implement the encryption formatting and mounting specifics
- [x] Add mkinitcpio configurations in grub bundle if there is an encrypted partitions 
- [x] Add grub configurations in grub bundle if there is an encrypted partitions
- [x] Test and debug

### CODE REVIEW

**Comment by Neo-29** [comment]
If you need tests when over with this pull request when over. Just tell me. 👍

**Comment by Rawleenc** [comment]
Development is done already, need to test in a VM to validate the feature and fixe all bugs if any.

**Comment by Neo-29** [comment]
> Development is done already, need to test in a VM to validate the feature and fixe all bugs if any.

Ok.
I'll test too if needed. 😃

**Comment by Rawleenc** [comment]
The launcher can be modified to fetch the `encryption` branch in a vm to test the PR.

**Comment by Rawleenc** [comment]
Any help/feedback will be very appreciated ! :smile:

**Comment by Neo-29** [comment]
> The launcher can be modified to fetch the `encryption` branch in a vm to test the PR.

If some steps to perform,you can give them to me. I'll try to have a go

**Comment by Rawleenc** [comment]
This line in the launcher define the branch to fetch
https://github.com/Rawleenc/ArchCraftsman/blob/4e37e0a7f1c419b737d14c9be11c20cce3bfdd2b/launcher.py#L14
So if you want to test you can copy the launcher in your Arch VM and then change this variable to fetch the `encryption` branch. This way, executing the launcher with `python launcher.py` will download and run this PR branch.
The launcher is an independent python script that can run alone.

**Comment by Neo-29** [comment]
> This line in the launcher define the branch to fetch
> 
> https://github.com/Rawleenc/ArchCraftsman/blob/4e37e0a7f1c419b737d14c9be11c20cce3bfdd2b/launcher.py#L14
> 
> 
> So if you want to test you can copy the launcher in your Arch VM and then change this variable to fetch the `encryption` branch. This way, executing the launcher with `python launcher.py` will download and run this PR branch.
> The launcher is an independent python script that can run alone.

I'll try that when I have time

**Comment by Rawleenc** [comment]
I managed to install and start an encrypted VM with the current state of the branch.
I installed the VM with the automatic partitioning.
Therefore, more tests need to be done to identify and fix all potentially remaining issues.

**Pull request merged**
